/**
 * Dump Master Data only → supabase/seed.sql
 *
 * Usage: npm run generate-seed
 *
 * Prefers `pg_dump` on PATH; falls back to `docker exec` into the local
 * Supabase Postgres container. Connection defaults to local Supabase
 * (override with SUPABASE_DB_URL / DATABASE_URL).
 */

import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const TABLES = [
  "contacts",
  "mst_brands",
  "mst_categories",
  "mst_colors",
  "mst_genders",
  "mst_sizes",
  "product_models",
  "products",
  "vendor_product_mapping",
  // mst_expense_categories ถูก seed ใน migration แล้ว (ON CONFLICT) — ไม่ dump ทับ
];

const OUT = resolve("supabase/seed.sql");
const DEFAULT_DB_URL =
  process.env.SUPABASE_DB_URL ||
  process.env.DATABASE_URL ||
  "postgresql://postgres:postgres@127.0.0.1:54322/postgres";

function run(cmd, args, opts = {}) {
  return spawnSync(cmd, args, {
    encoding: "utf8",
    shell: false,
    ...opts,
  });
}

function buildPgDumpArgs(connectionTarget, { useDockerDb = false } = {}) {
  // --inserts / --column-inserts → INSERT INTO ... VALUES (ไม่ใช้ COPY ที่ทำให้
  // Supabase db reset พังจาก psql meta / escape sequences)
  const args = [
    ...(useDockerDb ? ["-U", "postgres"] : []),
    "--data-only",
    "--no-owner",
    "--no-privileges",
    "--inserts",
    "--column-inserts",
    "--rows-per-insert=100",
  ];
  for (const table of TABLES) {
    args.push("-t", `public.${table}`);
  }
  if (!useDockerDb) {
    args.push(connectionTarget);
  } else {
    args.push(connectionTarget); // database name
  }
  return args;
}

/**
 * pg_dump 17+ แทรก \restrict / \unrestrict (psql meta) ซึ่งทำให้
 * supabase db reset เจอ SQL Syntax Error เมื่อรันผ่าน SQL executor
 */
function sanitizeSeedSql(sql) {
  return sql
    .replace(/^\uFEFF/, "")
    .split(/\r?\n/)
    // ตัด psql meta (\restrict / \unrestrict / อื่นๆ) ที่ทำให้ SQL executor พัง
    .filter((line) => !/^\\/.test(line.trim()))
    // PG17 SET ที่บาง executor ไม่รองรับ
    .filter((line) => !/^SET\s+transaction_timeout\b/i.test(line.trim()))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

function tryLocalPgDump() {
  const result = run("pg_dump", buildPgDumpArgs(DEFAULT_DB_URL));
  if (result.error?.code === "ENOENT") {
    return null;
  }
  return result;
}

function tryDockerPgDump() {
  const ps = run("docker", [
    "ps",
    "--format",
    "{{.Names}}",
    "--filter",
    "name=supabase_db_",
  ]);
  if (ps.status !== 0 || !ps.stdout?.trim()) {
    return {
      status: 1,
      stderr:
        "ไม่พบ container supabase_db_* — รัน `npx supabase start` ก่อน หรือติดตั้ง PostgreSQL client (pg_dump)",
      stdout: "",
    };
  }
  const container = ps.stdout
    .trim()
    .split(/\r?\n/)
    .find((name) => name.includes("supabase_db_"));
  if (!container) {
    return {
      status: 1,
      stderr: "ไม่พบ container supabase_db_*",
      stdout: "",
    };
  }

  return run("docker", [
    "exec",
    "-i",
    container,
    "pg_dump",
    ...buildPgDumpArgs("postgres", { useDockerDb: true }),
  ]);
}

const header = `-- =============================================================================
-- Supabase Seed — Master Data (generated by npm run generate-seed)
-- Tables: ${TABLES.join(", ")}
-- Generated at: ${new Date().toISOString()}
-- =============================================================================

`;

let result = tryLocalPgDump();
if (!result) {
  console.log("pg_dump ไม่พบใน PATH — ลองผ่าน Docker (supabase_db_*)...");
  result = tryDockerPgDump();
}

if (!result || result.status !== 0) {
  console.error(result?.stderr || result?.error || "generate-seed ล้มเหลว");
  process.exit(result?.status || 1);
}

const body = sanitizeSeedSql(result.stdout || "");
writeFileSync(OUT, header + body, "utf8");
console.log(`Wrote ${OUT} (${TABLES.length} tables)`);
